### ISSUE TITLE
卡片样式是否可以做成小Cai bot的风格？

### ISSUE THREAD

**Issue by Misaka-Mikoto-Tech** [ElainaFanBoy/nonebot_plugin_githubcard#2]
卡片样式可以做成小Cai bot那样吗，就是这种风格的
![)4_1XGH$}{0$YBFPR`W51VP_tmb](https://github.com/ElainaFanBoy/nonebot_plugin_githubcard/assets/1246379/ff04499f-d723-4106-8b3f-832d80df1cb8)

这个bot仓库地址是 https://github.com/cscs181/QQ-GitHub-Bot
但它功能太多了，我就只想要发送一个卡片的功能，[nonebot_plugin_githubcard](https://github.com/ElainaFanBoy/nonebot_plugin_githubcard) 符合我的需求，就是卡片样式数据有点少

**Comment by ElainaFanBoy** [comment]
你是说类似 https://github.com/Mcayear/koishi-plugin-github-opengraph 这种吗

最近有点忙，你可以先参考这个插件自己抄一个，应该不是很复杂
